apiVersion: v1
kind: Pod
metadata:
        # (name of the POD)
        name: nginxv1
        labels:
                app: webapp
                type: front-end
spec:
        containers:
                #(name of the container in the POD)
                - name: nginx-webserver
                  image: nginx
