kind: PersistentVolume
apiVersion: v1
metadata:
   name: pv-nfs
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: 10Gi
   accessModes:
    - ReadWriteOnce 
   nfs:
    server: 192.168.182.16
    path: /mnt/nfs